USE [master]
GO
CREATE DATABASE [SportProfilesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sn', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\db_a77d2b_spdb_data.mdf' , SIZE = 69504KB , MAXSIZE = 1024000KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sn_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\db_a77d2b_spdb_log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SportProfilesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SportProfilesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SportProfilesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SportProfilesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SportProfilesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SportProfilesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SportProfilesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SportProfilesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SportProfilesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SportProfilesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SportProfilesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SportProfilesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SportProfilesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SportProfilesDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SportProfilesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SportProfilesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SportProfilesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SportProfilesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SportProfilesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SportProfilesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SportProfilesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SportProfilesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SportProfilesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SportProfilesDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SportProfilesDB] SET  MULTI_USER 
GO

ALTER DATABASE [SportProfilesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SportProfilesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SportProfilesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SportProfilesDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SportProfilesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SportProfilesDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SportProfilesDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SportProfilesDB] SET  READ_WRITE 
GO


